name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Hello :wave:\nThank you for your contribution. At the moment this project is not accepting pull requests. Please see https://github.com/davecheney/pub#contributions.\nThank you in advance for your understanding."